### ISSUE TITLE
Add the S3 Bucket of China region to the document

### ISSUE THREAD

**Issue by FeynmanZhou** [aws-quickstart/quickstart-qingcloud-kubesphere#36]
@troy-ameigh  Can we add all the S3 Bucket of China region to this table? It only contains the US region in the table.
![image](https://user-images.githubusercontent.com/40452856/98829918-bbc52d80-2474-11eb-959c-a6c0a9c79547.png)

https://aws-quickstart.github.io/quickstart-qingcloud-kubesphere/#_sign_in_to_your_aws_account
![image](https://user-images.githubusercontent.com/40452856/98821832-0477e900-246b-11eb-8da2-85a2584e5e7c.png)

**Comment by troy-ameigh** [comment]
All I have this setup to go in as soon as we publish the current version

**Comment by troy-ameigh** [comment]
Closed by PR  #37
