### ISSUE TITLE
How to add the docs of Chinese version

### ISSUE THREAD

**Issue by FeynmanZhou** [aws-quickstart/quickstart-qingcloud-kubesphere#40]
@troy-ameigh 
We are preparing for the [deployment guide](https://github.com/aws-quickstart/quickstart-qingcloud-kubesphere/tree/main/docs/partner_editable) in Chinese version, how to submit them into this repository?

**Comment by troy-ameigh** [comment]
Please submit a Pull request to the develop branch:

Add the file to the "doc" folder

**Comment by FeynmanZhou** [comment]
> Please submit a Pull request to the develop branch:
> 
> Add the file to the "doc" folder

Ok, we will add them to a new PR soon.

**Comment by Sherlock113** [comment]
@troy-ameigh Hi Troy, just to confirm the source text to translate. Do we translate based on the adoc files in partner_editable in the develop branch? I noticed some parts in the deployment guide are actually missing in the folder partner_editable. For example, I cannot find sections in the blue box:

![image](https://user-images.githubusercontent.com/65327072/99634878-25989500-2a7c-11eb-9bba-73a7a995beaa.png)

**Comment by troy-ameigh** [comment]
You will need to translate everything from this site. https://aws-quickstart.github.io/quickstart-qingcloud-kubesphere/ 

I Recommend that you print the site into a PDF and then translate. You can then use the translated pdf to attach to the site that is in region.

**Comment by troy-ameigh** [comment]
I have come up with a way to accomplish this. Follow the steps below:

1. Fork the repo if you have not already, or just do a pull on the develop branch. 
2. In the "docs-languages/docs-cn" folder, translate the following files:
  2a. Within the asciidoc files there are certian items that **MUST NOT** be translated.
       - Anything in curly brackets "{}" such as:
          -  {partner-product-short-name}
          -  {partner-product-name}
          -     {partner-company-name}
       - Anything dealing with the images being used.
  2b. In "docs-languages/docs-cn/boilerplate" folder:
       - cost.adoc
       - deployment_steps.adoc
       - disclaimer.adoc
       - introduction.adoc
       - overview.adoc
       - planning_deployment.adoc
  2c. In "docs-languages/docs-cn/partner_editable" folder:
      - _settings.adoc
         * Only change the following in this file. (For the rest leave them or it will possibly break the doc). 
            - :partner-product-name:
            - :partner-product-short-name:
            - :partner-company-name: 
            - :partner-contributors:
      - additional_info.adoc
      - architecture.adoc
      - deploy_steps.adoc
      - deployment_options.adoc
      - faq_troubleshooting.adoc
      - licenses.adoc
      - overview_target_and_usage.adoc
      - pre-reqs.adoc
      - product_description.adoc 
      - regions.adoc
      - specialized_knowledge.adoc 

Please let me know if you have any questions and when the PR is submitted.

**Comment by Sherlock113** [comment]
> I have come up with a way to accomplish this. Follow the steps below:
> 
> 1. Fork the repo if you have not already, or just do a pull on the develop branch.
> 2. In the "docs-languages/docs-cn" folder, translate the following files:
>    2a. Within the asciidoc files there are certian items that **MUST NOT** be translated.
>    - Anything in curly brackets "{}" such as:
>    -  {partner-product-short-name}
>    -  {partner-product-name}
>    -     {partner-company-name}
>    - Anything dealing with the images being used.
>    2b. In "docs-languages/docs-cn/boilerplate" folder:
>    - cost.adoc
>    - deployment_steps.adoc
>    - disclaimer.adoc
>    - introduction.adoc
>    - overview.adoc
>    - planning_deployment.adoc
>    2c. In "docs-languages/docs-cn/partner_editable" folder:
>    
>    * _settings.adoc
>      
>      * Only change the following in this file. (For the rest leave them or it will possibly break the doc).
>        
>        * :partner-product-name:
>        * :partner-product-short-name:
>        * :partner-company-name:
>        * :partner-contributors:
>    * additional_info.adoc
>    * architecture.adoc
>    * deploy_steps.adoc
>    * deployment_options.adoc
>    * faq_troubleshooting.adoc
>    * licenses.adoc
>    * overview_target_and_usage.adoc
>    * pre-reqs.adoc
>    * product_description.adoc
>    * regions.adoc
>    * specialized_knowledge.adoc
> 
> Please let me know if you have any questions and when the PR is submitted.

Thanks. Just one thing about the section Parameter reference. The text in this part is not in the "docs-languages/docs-cn" folder. I think we still need to translate this part? Do we need to create the adoc file for this part by ourself?

![image](https://user-images.githubusercontent.com/65327072/99748255-23374900-2b17-11eb-9370-5bb5c6f227c4.png)

**Comment by FeynmanZhou** [comment]
> @troy-ameigh
> 
> Thanks. Just one thing about the section **Parameter reference**. The text in this part is not in the "docs-languages/docs-cn" folder. I think we still need to translate this part? Do we need to create the adoc file for this part by ourself?
> 
> Besides, I believe some text in the file _layout_cfn.adoc in "docs-languages/docs-cn/boilerplate" folder also needs to be translated as they are the text in the section **Send us feedback**, **Quick Start reference deployments** and **GitHub repository**.
> 
> ![image](https://user-images.githubusercontent.com/65327072/99748255-23374900-2b17-11eb-9370-5bb5c6f227c4.png)

I just find the content of the table below are located in the [yaml file](https://github.com/aws-quickstart/quickstart-qingcloud-kubesphere/blob/9d041af47dbcb911540146029820178de0c589d0/templates/kubesphere-entrypoint-existing-vpc.template.yaml#L139), how can we translate them?

**Comment by troy-ameigh** [comment]
The problem with the parameters is that they are automatically generated even for the the English version. So there is no file for them as they get pulled from the templates at document creation and recreation.

**Comment by troy-ameigh** [comment]
This is complete see https://aws-quickstart.github.io/quickstart-qingcloud-kubesphere/index-cn.html for Chinese version of dos/

**Comment by FeynmanZhou** [comment]
> This is complete see https://aws-quickstart.github.io/quickstart-qingcloud-kubesphere/index-cn.html for Chinese version of dos/

@Sherlock113 The images are broken, could you pls check them? 
![image](https://user-images.githubusercontent.com/40452856/102951517-00c69000-4508-11eb-8f12-507cbd1236f4.png)

**Comment by Sherlock113** [comment]
> > This is complete see https://aws-quickstart.github.io/quickstart-qingcloud-kubesphere/index-cn.html for Chinese version of dos/
> 
> @Sherlock113 The images are broken, could you pls check them?
> ![image](https://user-images.githubusercontent.com/40452856/102951517-00c69000-4508-11eb-8f12-507cbd1236f4.png)

Perhaps that is because the name description of the image. I did not change the image itself. Only the name was translated.
