### ISSUE TITLE
Failed to create quickstart in China (Beijing) region

### ISSUE THREAD

**Issue by FeynmanZhou** [aws-quickstart/quickstart-qingcloud-kubesphere#42]
I used the following URL to create a cloudformation stack in China (Beijing) region, but it returns the following error logs. 

https://aws-quickstart-cn-north-1.s3.cn-north-1.amazonaws.com.cn/quickstart-qingcloud-kubesphere/templates/kubesphere-entrypoint-new-vpc.template.yaml

![image](https://user-images.githubusercontent.com/40452856/99259007-5bf3cb80-2854-11eb-84cf-81762a9b46ef.png)

**Comment by troy-ameigh** [comment]
This was caused by the Number of AZ's not being changed to 2 from 3. As CN-North-1 only has 2 az's. I am adding a rule to help with this issue.

**Comment by troy-ameigh** [comment]
Updated in PR[ #41](https://github.com/aws-quickstart/quickstart-qingcloud-kubesphere/pull/41)

**Comment by FeynmanZhou** [comment]
@troy-ameigh Thanks, we will verify it soon!
