### ISSUE TITLE
_init_() got an unexpected keyword argument 'previousSystemTags' (TypeError)

### ISSUE THREAD

**Issue by Forest-L** [aws-quickstart/quickstart-qingcloud-kubesphere#43]
When creating the ALBIngressStack, the following error was reported and encountered three times. I don't know what triggered it.

![image](https://user-images.githubusercontent.com/50984129/99263610-687b2280-285a-11eb-9602-cc6acea8b361.png)

**Comment by troy-ameigh** [comment]
This is fixed, in both our Kubesphere stack an in the main EKS QS. I am pushing updates through.

**Comment by troy-ameigh** [comment]
Update was pushed in [PR #44](https://github.com/aws-quickstart/quickstart-qingcloud-kubesphere/pull/44)
