### ISSUE TITLE
China region link fix

### ISSUE THREAD

**Issue by Sherlock113** [aws-quickstart/quickstart-qingcloud-kubesphere#59]
Hi @troy-ameigh,

There are link issues in the deployment guide and landing page that we cannot fix directly.

[In the deployment guide](https://aws-quickstart.github.io/quickstart-qingcloud-kubesphere/):

1. The link Deploy KubeSphere into a new VPC on AWS into CN-North-1 Region should direct users to the China region. 

![image](https://user-images.githubusercontent.com/65327072/103333822-2f191200-4aaa-11eb-93de-6c6e0fa2305f.png)

Namely, when they are logged in, they are supposed to see the China region (Ningxia & Beijing) with the new vpc template URL shown in the field **Amazon S3 URL**. If they are not logged in, they are supposed to see the [login page](https://console.amazonaws.cn/cloudformation/home?region=cn-north-1#/) (China region) when they click the link. However, the current link still directs users to the global login page.

2. The link Deploy KubeSphere into an existing VPC on AWS into CN-Northwest-1 Region also has the same issue. Users are supposed to see the China region with the existing vpc template.

[On the landing page](https://aws.amazon.com/cn/quickstart/architecture/qingcloud-kubesphere/) these two links have the same issue as above. Users need to see the China region page instead of the global one.

![image](https://user-images.githubusercontent.com/65327072/103334489-743e4380-4aac-11eb-8e1a-99161dd1d1d8.png)

Could you please help us fix these links? Thanks.

**Comment by troy-ameigh** [comment]
We are looking into this.

**Comment by troy-ameigh** [comment]
Resolved
