### ISSUE TITLE
How to upgrade EKS by marketplaces.

### ISSUE THREAD

**Issue by ruiyaoOps** [aws-quickstart/quickstart-qingcloud-kubesphere#73]
@troy-ameigh 
Hello troy,
  I want to create a marketplace to update KES and our app, but I do not find the way to upgrade EKS in https://github.com/aws-quickstart, so do you know how to upgrade EKS by marketplaces.
Looking forward to your reply.
Thank you.

**Comment by troy-ameigh** [comment]
To upgrade EKS with in the quickstart, you need to update the EKS submodule, by doing the following. 

1. Do a git pull from this upstream repo to your fork. (insures you have the latest version)
2. Do the following commands in your forked repo:

git submodule sync
git submodule update --init --remote submodules/quickstart-amazon-eks
git commit -m "update submodule" submodules/quickstart-amazon-eks
git submodule update --init --recursive
git push

3. Test deployment with lastest version of EKS Submodule and correct issues if any occur.
4. Create a new PR to our repo with all committed changes. 

Please let me know if you have any questions.

**Comment by ruiyaoOps** [comment]
Thank you for your reply.
  If a user has already deployed EKS and KubeSphere, can I upgrade the existing EKS cluster through the QuickStart Marketplace. 
  I think we can do it with AWS CLI, but using user password authentication is not elegant, is there any other way to authorize ProvisionBastionHost.

**Comment by troy-ameigh** [comment]
ruiyaoOps - The problem, with doing a stack update of the QS is there is no rollback capability. So if the update fails or has an issue, you could be stuck in an unusable state. Theoretically the command line update should work, however it is untested by us. The best course would be to stand up a new cluster using the kubesphere QS and migrate to it.
