### ISSUE TITLE
Delete resource KubeSphereUser

### ISSUE THREAD

**Issue by ruiyaoOps** [aws-quickstart/quickstart-qingcloud-kubesphere#74]
hello @troy-ameigh 
We will update the new version, and I found that we defined KubeSphereUser stack in the Resources of the Kubesphere.template.yaml file to set the admin user password of KubeSphere, but I think this is not necessary, because when logging in to the KubeSphere console for the first time, We will require the user to change the password of the admin user.
![image](https://user-images.githubusercontent.com/35256376/147637726-30336448-406a-4088-a510-40bf1e55a5dd.png)

I think this needs to be notified to you, and deleted after you confirm it.
Looking forward to your reply, thank you.

**Comment by troy-ameigh** [comment]
@ruiyaoOps I have tried removing the Password for this and everytime the stack fails to build, as something in the Manifest is looking for it to be set. Can you please advise on how you want to proceed. Thank you

**Comment by ruiyaoOps** [comment]
Happy new year @troy-ameigh 
It failed because the resource KubeSphereUpdatePassword Outputs and so on will use KubeSphereConsolePassword.

If created the resource is deleted through CloudFormation after the installation is completed, the deletion of the resources will fail. This is because the KubeSphereUpdatePassword resource is included in the KubeSphere resource, and the KubeSphereUpdatePassword will be used when the KubeSphere resource is deleted, failing to delete the KubeSphereUpdatePassword.
I will fix these in new version by update KubeSphere version and removed Resources KubeSphereUser KubeSphereUpdatePassword GlobalRoleBinding KubeSphereServiceAccount KubeSphereClusterRoleBinding and KubeSphereGlobalRoleBinding in kubesphere.template.yaml.

I can provide you with the new templates by mail or other means, do you need to try it?

**Comment by ruiyaoOps** [comment]
In the new version of KubeSphere, We will automatically install the resources required by KubeSphere and require the administrator user to change the administrator user password when they log in for the first time.

**Comment by troy-ameigh** [comment]
Can you please push a PR over to the "main" branch so we can test and incorporate. Thank you
