### ISSUE TITLE
The code in S3 is not updated

### ISSUE THREAD

**Issue by ruiyaoOps** [aws-quickstart/quickstart-qingcloud-kubesphere#76]
hello @troy-ameigh 
We tested on [aws](https://aws.amazon.com/quickstart/architecture/qingcloud-kubesphere/) and found that the code is not the latest, what should we do?

**Comment by ruiyaoOps** [comment]
<img width="935" alt="image" src="https://user-images.githubusercontent.com/35256376/155477079-7adf918a-4ba4-474e-b98c-4c6bf1a209d3.png">
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/35256376/155477147-eba08f38-2ac5-4d4d-be12-4a6d1c5cd1a4.png">

**Comment by ruiyaoOps** [comment]
@troy-ameigh  We reconfirmed that the code in https://aws-quickstart.s3.amazonaws.com/quickstart-qingcloud-kubesphere/ is not updated

**Comment by troy-ameigh** [comment]
@ruiyaoOps I am looking into this

**Comment by troy-ameigh** [comment]
@ruiyaoOps bucket sync issue resolved. Buckets are now lastest.
