### ISSUE TITLE
failed to run EKSClusterStack AutoDetectSharedResources

### ISSUE THREAD

**Issue by lanlin** [aws-quickstart/quickstart-qingcloud-kubesphere#79]
```shell
Kubesphere-EKSClusterStack-VWWCKS0C1UFP-AutoDetectSharedResources-4TA3HXRTODWW
The following resource(s) failed to create: [PreReqs].
```

```shell
PreReqs
CloudFormation did not receive a response from your Custom Resource. 
Please check your logs for requestId [10d1fec4-4a11-4a88-8b0b-b64498a398de]. 
If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.
```

https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-cfn-response-lambda/

**Comment by ruiyaoOps** [comment]
This is a bug of EKS quickstart, get more from:  https://github.com/aws-quickstart/quickstart-amazon-eks/issues/397

**Comment by ruiyaoOps** [comment]
we will update the submodule to fix it later.

**Comment by troy-ameigh** [comment]
I have pushed some updates that should be in S3 shortly

**Comment by lanlin** [comment]
nice work, with much thanks

**Comment by lanlin** [comment]
@troy-ameigh I have tried in area ap-southeast-2, same error again

![image](https://user-images.githubusercontent.com/3468024/161189323-bbfda03c-f7bc-42f8-a5ec-e40ec02db406.png)

**Comment by lanlin** [comment]
I also got an error from the health dashboard, could it be caused by the quickstart?

![image](https://user-images.githubusercontent.com/3468024/161190301-d2f2810f-d4e4-4ef1-8b90-c541b8a9209c.png)

**Comment by ruiyaoOps** [comment]
Not fix yet, please follow the issue https://github.com/aws-quickstart/quickstart-amazon-eks/issues/397

**Comment by troy-ameigh** [comment]
@ruiyaoOps I am getting a successful build minus and issue with the Bastion.

**Comment by troy-ameigh** [comment]
There is a new update in S3 as of tonight. Issue should be resolved. I am working on updating your submodule.

**Comment by troy-ameigh** [comment]
Submodule is updates with latest fixes, please try it.

**Comment by lanlin** [comment]
got an error when running on this step below:

```shell
qingcloud-kubesphere-EKSClusterStack-1DKFR4UKVNFTL-EKSStack-RKKGQ9XPTLVC-BastionStack-12BIOWXK9PQGI
LinuxBastion+VPC Jul,30,2020 (qs-1qup6ra99) (Please do not remove)
```
```shell
CREATE_FAILED
The following resource(s) failed to create: [EIP1].
```

**Comment by ruiyaoOps** [comment]
This issue has been confirmed to be resolved, I will close it.

**Comment by ruiyaoOps** [comment]
@lanlin  please create a new issue for the new error.
