### ISSUE TITLE
BastionAutoScalingGroup - Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

### ISSUE THREAD

**Issue by andrerkn** [aws-quickstart/quickstart-qingcloud-kubesphere#83]
Hey guys.
I am trying to deploy Kubesphere using this template and I am getting the error below:

**BastionAutoScalingGroup**
Received FAILURE signal with UniqueId i-0b2a87b90c296d573

**BastionAutoScalingGroup**
Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

**BastionStack**
The following resource(s) failed to create: [BastionAutoScalingGroup]. 

I followed some steps here to diagnose:
 
```
[ec2-user@ip-10-0-137-242 ~]$ sudo find / -name cfn-signal
/usr/bin/cfn-signal
/opt/aws/bin/cfn-signal
/opt/aws/apitools/cfn-init-2.0-10/bin/cfn-signal
```

```
[ec2-user@ip-10-0-137-242 ~]$ sudo rpm -q aws-cfn-bootstrap
aws-cfn-bootstrap-2.0-10.amzn2.noarch
```

```
[root@ip-10-0-137-242 ~]# grep -ni 'error\|failure' $(sudo find /var/log -name cfn\* -or -name cloud-init\*)
/var/log/cloud-init.log:483:Apr 04 15:20:38 cloud-init[2099]: main.py[DEBUG]: Ran 14 modules with 0 failures
/var/log/cloud-init.log:585:Apr 04 15:20:57 cloud-init[2305]: main.py[DEBUG]: Ran 10 modules with 0 failures
/var/log/cloud-init.log:618:    raise ProcessExecutionError(stdout=out, stderr=err,
/var/log/cloud-init.log:619:ProcessExecutionError: Unexpected error while running command.
/var/log/cloud-init.log:640:RuntimeError: Runparts: 1 failures in 1 attempted commands
/var/log/cloud-init.log:676:Apr 04 15:23:40 cloud-init[6700]: main.py[DEBUG]: Ran 9 modules with 1 failures
/var/log/cloud-init-output.log:495:--> Processing Dependency: perl(Error) for package: perl-Git-2.32.0-1.amzn2.0.1.noarch
/var/log/cloud-init-output.log:498:---> Package perl-Error.noarch 1:0.17020-2.amzn2 will be installed
/var/log/cloud-init-output.log:512: perl-Error           noarch     1:0.17020-2.amzn2         amzn2-core      32 k
/var/log/cloud-init-output.log:531:  Installing : 1:perl-Error-0.17020-2.amzn2.noarch                          3/7 
/var/log/cloud-init-output.log:542:  Verifying  : 1:perl-Error-0.17020-2.amzn2.noarch                          7/7 
/var/log/cloud-init-output.log:551:  perl-Error.noarch 1:0.17020-2.amzn2                                           
/var/log/cloud-init-output.log:1464:+ curl --silent --show-error --retry 5 https://bootstrap.pypa.io/pip/2.7/get-pip.py
/var/log/cloud-init-output.log:1532:Error occurred during build: Command b-bootstrap failed
/var/log/cfn-init.log:33:2022-04-04 15:23:40,188 [ERROR] Command b-bootstrap (./bastion_bootstrap.sh --banner s3://aws-quickstart-us-east-1/quickstart-qingcloud-kubesphere/submodules/quickstart-amazon-eks/scripts/bastion_banner_message.txt --enable true --tcp-forwarding false --x11-forwarding false) failed
/var/log/cfn-init.log:205:2022-04-04 15:23:40,188 [ERROR] Error encountered during build of config: Command b-bootstrap failed
/var/log/cfn-init.log:212:    raise ToolError(u"Command %s failed" % name)
/var/log/cfn-init.log:213:cfnbootstrap.construction_errors.ToolError: Command b-bootstrap failed
/var/log/cfn-init.log:214:2022-04-04 15:23:40,191 [ERROR] -----------------------BUILD FAILED!------------------------
/var/log/cfn-init.log:215:2022-04-04 15:23:40,191 [ERROR] Unhandled exception during build: Command b-bootstrap failed
/var/log/cfn-init.log:228:    raise ToolError(u"Command %s failed" % name)
/var/log/cfn-init.log:229:cfnbootstrap.construction_errors.ToolError: Command b-bootstrap failed
/var/log/cfn-init.log:231:2022-04-04 15:23:40,536 [DEBUG] Signaling resource BastionAutoScalingGroup in stack KubesphereMcx-EKSClusterStack-HDWTSIGVG3ZK-EKSStack-10A39EN04GUON-BastionStack-DKCAER5QS9WG with unique ID i-0b2a87b90c296d573 and status FAILURE
/var/log/cfn-wire.log:4:2022-04-04 15:23:40,599 [DEBUG] Response: 200 https://cloudformation.us-east-1.amazonaws.com/?Action=SignalResource&LogicalResourceId=BastionAutoScalingGroup&StackName=KubesphereMcx-EKSClusterStack-HDWTSIGVG3ZK-EKSStack-10A39EN04GUON-BastionStack-DKCAER5QS9WG&UniqueId=i-0b2a87b90c296d573&Status=FAILURE&ContentType=JSON&Version=2010-05-15 [headers: {'x-amzn-RequestId': 'cfc806a2-d207-4a0b-8f42-d2b41b905a3d', 'Content-Type': 'application/json', 'Content-Length': '100', 'Date': 'Mon, 04 Apr 2022 15:23:40 GMT'}]
/var/log/cfn-init-cmd.log:259:2022-04-04 15:23:40,187 P10586 [ERROR] Exited with error code 1
```

**Parameters used in Cloudformation template:**

**Key - Value**
Alerting - false
Auditing - false
AvailabilityZones - us-east-1a,us-east-1b,us-east-1c
Devops - false
EKSClusterName - KubesphereMcx
Events - false
KeyPairName - *******
Kubeedge - false
Logging - false
MetricsServer - true
Multicluster - none 
Networkpolicy - false
NodeInstanceType - t3.medium
NumberOfAZs - 3
NumberOfNodes - 3
Openpitrix - false
PerAccountSharedResources - AutoDetect
PerRegionSharedResources - AutoDetect
PrivateSubnet1CIDR - 10.0.0.0/19
PrivateSubnet2CIDR - 10.0.32.0/19
PrivateSubnet3CIDR - 10.0.64.0/19
ProvisionBastionHost - Enabled
PublicSubnet1CIDR - 10.0.128.0/20
PublicSubnet2CIDR - 10.0.144.0/20
PublicSubnet3CIDR - 10.0.160.0/20
QSS3BucketName - aws-quickstart
QSS3BucketRegion - us-east-1
QSS3KeyPrefix - quickstart-qingcloud-kubesphere/
RemoteAccessCIDR - 0.0.0.0/0
Servicemesh - false
VPCCIDR - 10.0.0.0/16

Can you help me?

Thanks
Andre

**Comment by andrerkn** [comment]
![Screenshot from 2022-04-04 12-38-12](https://user-images.githubusercontent.com/55511334/161583827-5797bdd7-8e67-4224-bafb-92c26fa33133.png)

**Comment by ruiyaoOps** [comment]
You can check the status of the Auto Scaling group in ec2, I think the EKS resource was created successfully.
This may be a bug in eks quickstart, I will verify

**Comment by ruiyaoOps** [comment]
I think the reason for this problem is that the security group created by EKS quickstart has no inbound rules, it should allow access to 0.0.0.0/0.

**Comment by ruiyaoOps** [comment]
I have create a issue https://github.com/aws-quickstart/quickstart-amazon-eks/issues/411, please provide more information there.

**Comment by andrerkn** [comment]
Hey ruiyaoOps,

Cloudformation created two AutoScaling Groups:
- BastionAutoScalingGroup
- eksDefault

Health of both are ok:
![Screenshot from 2022-04-06 15-47-45](https://user-images.githubusercontent.com/55511334/162046901-a3563b52-2a34-4f99-bb54-2ce6fd96b259.png)
![Screenshot from 2022-04-06 15-47-56](https://user-images.githubusercontent.com/55511334/162046919-fb627832-8d84-4bb8-b576-dad9e691b32c.png)

eksDefault AutoScaling Group has no SecurityGroup attached. Is this the cause of Cloudformation error?:
![Screenshot from 2022-04-06 15-49-39](https://user-images.githubusercontent.com/55511334/162047139-d07718e6-abaf-4d5b-85e8-2f639a88f3b7.png)

BastionAutoScaling group has a SG:
![Screenshot from 2022-04-06 15-50-51](https://user-images.githubusercontent.com/55511334/162047289-e7a2e302-41ce-45d2-a893-f0e8ec7ab465.png)

EC2 status are ok:
![Screenshot from 2022-04-06 15-51-33](https://user-images.githubusercontent.com/55511334/162047439-805bd3fe-21ad-41db-9732-afacf2df0bae.png)

EKS Cluster and NodeGroup looks ok too:

![Screenshot from 2022-04-06 15-52-48](https://user-images.githubusercontent.com/55511334/162048022-32c8b040-ff23-49f6-9d5c-f9a1b0c5c647.png)
![Screenshot from 2022-04-06 15-52-37](https://user-images.githubusercontent.com/55511334/162048042-4c4a5a9b-0d70-43dc-88aa-0f889f52832f.png)


André

**Comment by lanlin** [comment]
same error

| time |  ID | status | message |
| -- | -- | -- | -- | 
| 2022-04-07 14:16:05 UTC+0800 | Kubesphere-EKSClusterStack-8J49PBLVFNOO-EKSStack-69067SHS38QF-BastionStack-UVXJ2YYL91CQ | UPDATE_FAILED | The following resource(s) failed to create: [BastionAutoScalingGroup]. |
| 2022-04-07 14:16:02 UTC+0800 | BastionAutoScalingGroup | CREATE_FAILED | Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement |
| 2022-04-07 14:16:01 UTC+0800 | BastionAutoScalingGroup | CREATE_IN_PROGRESS | Received FAILURE signal with UniqueId i-0da2799135b96888d |
| 2022-04-07 14:08:16 UTC+0800 | BastionAutoScalingGroup | CREATE_IN_PROGRESS | Resource creation Initiated |
| 2022-04-07 14:08:15 UTC+0800 | BastionAutoScalingGroup | CREATE_IN_PROGRESS | -- |

**Comment by ruiyaoOps** [comment]
Now, you can only create a cluster through the EKS product on the AWS website, and then deploy KubeSphere by command-tool, until troy resolves the problem.

**Comment by troy-ameigh** [comment]
This is resolved.
