### ISSUE TITLE
Do we need to update the KubeSphere QuickStart submodule and S3 storage to the latest version?

### ISSUE THREAD

**Issue by ruiyaoOps** [aws-quickstart/quickstart-qingcloud-kubesphere#87]
hello @troy-ameigh 
The tester found that EKS QuickStart has no problem, but the KubeSphere QuickStart still gets errors. Do we need to update the KubeSphere QuickStart submodule and S3 storage to the latest version?
THX

**Comment by troy-ameigh** [comment]
Submodule updates appear to be in the buckets. Do we know which region and how they are launching the QS?

**Comment by ruiyaoOps** [comment]
Confirm the recovery, all processes completed successfully, we will update the documentation next.
Thank you very much @troy-ameigh
